#' @title HP Model: Chain's plot
#'
#' @description This function provides three types of plots for the chain generated by the MCMC
#' method in the hp() function.
#'
#' @usage
#' plot_chain(fit, type = c("trace", "acf", "density"))
#'
#' @param fit Object of the class 'HP' fitted by the hp() function.
#' @param type Character string specifying the type of plot to be returned. There are three options:
#' \itemize{trace: }{return a plot with the parameters' samples.}
#' \itemize{acf: }{return a plot with the autocorrelation of the parameters' samples.}
#' \itemize{density: }{return a plot with the posterior density of the paramaters based on the samples generated by the MCMC method.}
#'
#' @return A plot of the chosen type.
#'
#' @examples
#' ## Importing mortality data from USA
#' data(USA)
#'
#' ## Selecting the exposure and death count of the 2010 population ranging from 0 to 90 years old
#' USA2010 = USA[USA$Year == 2010,]
#' x = 0:90
#' Ex = USA2010$Ex.Total[x+1]
#' Dx = USA2010$Dx.Total[x+1]
#'
#' ## Fitting a model
#' fit = hp(x = x, Ex = Ex, Dx = Dx, model = "lognormal",
#'          M = 50000, bn = 10000, thin = 40,
#'          m = c(NA, 0.08, rep(NA, 6)),
#'          v = c(NA, 1e-4, rep(NA, 6)))
#'
#' ## Plotting all the available types of plot
#' plot_chain(fit, type = "trace")
#' plot_chain(fit, type = "acf")
#' plot_chain(fit, type = "density")
#'
#' @import ggplot2
#'
#' @export
plot_chain <- function(fit, type = c("trace", "acf", "density")){

  type = match.arg(type)

  if(type == "trace"){

    if(fit$info$model %in% c("binomial", "poisson")){
      df = data.frame(
        samples = c(fit$post.samples$mcmc_theta[,1], fit$post.samples$mcmc_theta[,2],
                    fit$post.samples$mcmc_theta[,3], fit$post.samples$mcmc_theta[,4],
                    fit$post.samples$mcmc_theta[,5], fit$post.samples$mcmc_theta[,6],
                    fit$post.samples$mcmc_theta[,7], fit$post.samples$mcmc_theta[,8]),
        param = rep(LETTERS[1:8], each = nrow(fit$post.samples$mcmc_theta)),
        iteration = rep(1:nrow(fit$post.samples$mcmc_theta), times = 8)
      )
    }else{
      df = data.frame(
        samples = c(fit$post.samples$mcmc_theta[,1], fit$post.samples$mcmc_theta[,2],
                    fit$post.samples$mcmc_theta[,3], fit$post.samples$mcmc_theta[,4],
                    fit$post.samples$mcmc_theta[,5], fit$post.samples$mcmc_theta[,6],
                    fit$post.samples$mcmc_theta[,7], fit$post.samples$mcmc_theta[,8],
                    fit$post.samples$sigma2),
        param = rep(c(LETTERS[1:8], "sigma2"), each = nrow(fit$post.samples$mcmc_theta)),
        iteration = rep(1:nrow(fit$post.samples$mcmc_theta), times = 9)
      )
    }

    ggplot2::ggplot(df) +
      ggplot2::xlab("") + ggplot2::ylab("") + ggplot2::theme_bw() +
      ggplot2::theme(plot.title = ggplot2::element_text(lineheight = 1.2),
                     axis.title.x = ggplot2::element_text(color = 'black', size = 13),
                     axis.title.y = ggplot2::element_text(color = 'black', size = 13),
                     axis.text = ggplot2::element_text(color = 'black', size = 13),
                     legend.text = ggplot2::element_text(size = 13),
                     strip.background = ggplot2::element_rect(fill = "deepskyblue4"),
                     strip.text = ggplot2::element_text(color = "white", size = 12)) +
      ggplot2::geom_line(ggplot2::aes(x = iteration, y = samples), col = "deepskyblue4") +
      ggplot2::facet_wrap(~param, scales = "free")

  }else if(type == "acf"){

    if(fit$info$model %in% c("binomial", "poisson")){
      df = data.frame(
        autocor = c(
          acf(fit$post.samples$mcmc_theta[,1], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,2], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,3], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,4], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,5], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,6], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,7], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,8], lag.max = 50, plot = F)$acf),
        param = rep(LETTERS[1:8], each = 51),
        lag = rep(0:50, times = 8)
      )
    }else{
      df = data.frame(
        autocor = c(
          acf(fit$post.samples$mcmc_theta[,1], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,2], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,3], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,4], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,5], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,6], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,7], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$mcmc_theta[,8], lag.max = 50, plot = F)$acf,
          acf(fit$post.samples$sigma2, lag.max = 50, plot = F)$acf),
        param = rep(c(LETTERS[1:8], "sigma2"), each = 51),
        lag = rep(0:50, times = 9)
      )
    }

    ggplot2::ggplot(df) +
      ggplot2::scale_y_continuous(breaks = seq(0, 1, by = 0.2)) +
      ggplot2::scale_x_continuous(breaks = seq(0, 50, by = 10), limits = c(-0.5, 50.5)) +
      ggplot2::xlab("Lag") + ggplot2::ylab("Autocorrelation") + ggplot2::theme_bw() +
      ggplot2::theme(plot.title = ggplot2::element_text(lineheight = 1.2),
                     axis.title.x = ggplot2::element_text(color = 'black', size = 13),
                     axis.title.y = ggplot2::element_text(color = 'black', size = 13),
                     axis.text = ggplot2::element_text(color = 'black', size = 13),
                     legend.text = ggplot2::element_text(size = 13),
                     strip.background = ggplot2::element_rect(fill = "deepskyblue4"),
                     strip.text = ggplot2::element_text(color = "white", size = 12)) +
      ggplot2::geom_bar(ggplot2::aes(x = lag, y = autocor), stat = "identity", col = "black", fill = "orangered4") +
      ggplot2::facet_wrap(~param)

  }else if(type == "density"){


    if(fit$info$model %in% c("binomial", "poisson")){
      df = data.frame(
        samples = c(fit$post.samples$mcmc_theta[,1], fit$post.samples$mcmc_theta[,2],
                    fit$post.samples$mcmc_theta[,3], fit$post.samples$mcmc_theta[,4],
                    fit$post.samples$mcmc_theta[,5], fit$post.samples$mcmc_theta[,6],
                    fit$post.samples$mcmc_theta[,7], fit$post.samples$mcmc_theta[,8]),
        param = rep(LETTERS[1:8], each = nrow(fit$post.samples$mcmc_theta)),
        iteration = rep(1:nrow(fit$post.samples$mcmc_theta), times = 8)
      )
    }else{
      df = data.frame(
        samples = c(fit$post.samples$mcmc_theta[,1], fit$post.samples$mcmc_theta[,2],
                    fit$post.samples$mcmc_theta[,3], fit$post.samples$mcmc_theta[,4],
                    fit$post.samples$mcmc_theta[,5], fit$post.samples$mcmc_theta[,6],
                    fit$post.samples$mcmc_theta[,7], fit$post.samples$mcmc_theta[,8],
                    fit$post.samples$sigma2),
        param = rep(c(LETTERS[1:8], "sigma2"), each = nrow(fit$post.samples$mcmc_theta)),
        iteration = rep(1:nrow(fit$post.samples$mcmc_theta), times = 9)
      )
    }

    ggplot2::ggplot(df) +
      ggplot2::xlab("") + ggplot2::ylab("") + ggplot2::theme_bw() +
      ggplot2::theme(plot.title = ggplot2::element_text(lineheight = 1.2),
                     axis.title.x = ggplot2::element_text(color = 'black', size = 13),
                     axis.title.y = ggplot2::element_text(color = 'black', size = 13),
                     axis.text = ggplot2::element_text(color = 'black', size = 13),
                     legend.text = ggplot2::element_text(size = 13),
                     strip.background = ggplot2::element_rect(fill = "deepskyblue4"),
                     strip.text = ggplot2::element_text(color = "white", size = 12)) +
      ggplot2::geom_density(ggplot2::aes(x = samples), col = "black", fill = "deepskyblue4", alpha = .7) +
      ggplot2::facet_wrap(~param, scales = "free")

  }else{
    stop("Invalid type.")
  }
}
